from typing import Dict, Any, List

class ExplainabilityEngine:
    """
    Generates human-readable justifications for plagiarism and AI detection results.
    """
    
    @staticmethod
    def explain_match(match_type: str, confidence: float, source_title: str = "") -> str:
        """Generates a brief explanation for a single match."""
        if match_type == "exact":
            return f"Verbatim match detected with '{source_title}'. Sentence structure and word choice are identical."
        
        if match_type == "semantic":
            desc = "High" if confidence > 0.9 else "Moderate"
            return f"{desc} semantic similarity detected. The ideas and context align closely with '{source_title}', suggesting paraphrasing."
        
        if match_type == "ai":
            return "Highly predictable sentence patterns detected. The sequence alignment matches statistical signatures common in Large Language Models (LLMs)."
            
        return "Pattern match detected."

    def generate_report_summary(self, scores: Dict[str, float]) -> str:
        """Generates a summary paragraph for the entire report."""
        summary = []
        
        if scores.get("exact", 0) > 20:
            summary.append("Significant verbatim plagiarism detected across multiple sections.")
        elif scores.get("semantic", 0) > 30:
            summary.append("Extensive paraphrasing and conceptual similarity identified.")
            
        if scores.get("ai", 0) > 70:
            summary.append("The document shows strong evidence of being generated by AI, with low lexical variance and high predictive regularity.")
            
        if not summary:
            return "No major originality issues detected. The document appears consistent with original human writing."
            
        return " ".join(summary)
